# Generated by Django 4.1 on 2022-08-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('seller_name', models.CharField(max_length=100)),
                ('stock_num', models.BigIntegerField()),
                ('ratings', models.BigIntegerField()),
            ],
        ),
    ]
